// go-match is a command-line utility to check if paths match include patterns and don't match exclude patterns.
package main

import (
	"fmt"
	"os"

	"github.com/idelchi/go-match/internal/logic"
)

// version is the application version injected at build time.
var version = "unknown - unofficial & generated by unknown"

// main is the entry point of the application.
func main() {
	if err := logic.Run(version); err != nil {
		fmt.Fprintf(os.Stderr, "running the application: %v\n", err)

		os.Exit(1)
	}

	os.Exit(0)
}
